spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  datasource:
    jdbc-url: jdbc:sqlserver://STROUSTRUP-PC\SQLEXPRESS;database=ArchiveFund;trustServerCertificate=true;
    username: sa
    password: MiKe_5526

  access-enabled: true
  access-datasource:
    jdbc-url: jdbc:ucanaccess://G:\test.mdb;memory=false;openExclusive=true;ignoreCase=true

  main:
    banner-mode: off

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
